package com.xx.chinetek.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xx.chinetek.model.Base.MaterialModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MATERIAL_MODEL".
*/
public class MaterialModelDao extends AbstractDao<MaterialModel, Void> {

    public static final String TABLENAME = "MATERIAL_MODEL";

    /**
     * Properties of entity MaterialModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MATNR = new Property(0, String.class, "MATNR", false, "MATNR");
        public final static Property MTART = new Property(1, String.class, "MTART", false, "MTART");
        public final static Property MATKL = new Property(2, String.class, "MATKL", false, "MATKL");
        public final static Property BISMT = new Property(3, String.class, "BISMT", false, "BISMT");
        public final static Property NORMT = new Property(4, String.class, "NORMT", false, "NORMT");
        public final static Property SPART = new Property(5, String.class, "SPART", false, "SPART");
        public final static Property MAKTX = new Property(6, String.class, "MAKTX", false, "MAKTX");
        public final static Property ZMAKTX = new Property(7, String.class, "ZMAKTX", false, "ZMAKTX");
        public final static Property ZEINR = new Property(8, String.class, "ZEINR", false, "ZEINR");
    }


    public MaterialModelDao(DaoConfig config) {
        super(config);
    }
    
    public MaterialModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MATERIAL_MODEL\" (" + //
                "\"MATNR\" TEXT UNIQUE ," + // 0: MATNR
                "\"MTART\" TEXT," + // 1: MTART
                "\"MATKL\" TEXT," + // 2: MATKL
                "\"BISMT\" TEXT," + // 3: BISMT
                "\"NORMT\" TEXT," + // 4: NORMT
                "\"SPART\" TEXT," + // 5: SPART
                "\"MAKTX\" TEXT," + // 6: MAKTX
                "\"ZMAKTX\" TEXT," + // 7: ZMAKTX
                "\"ZEINR\" TEXT);"); // 8: ZEINR
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MATERIAL_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MaterialModel entity) {
        stmt.clearBindings();
 
        String MATNR = entity.getMATNR();
        if (MATNR != null) {
            stmt.bindString(1, MATNR);
        }
 
        String MTART = entity.getMTART();
        if (MTART != null) {
            stmt.bindString(2, MTART);
        }
 
        String MATKL = entity.getMATKL();
        if (MATKL != null) {
            stmt.bindString(3, MATKL);
        }
 
        String BISMT = entity.getBISMT();
        if (BISMT != null) {
            stmt.bindString(4, BISMT);
        }
 
        String NORMT = entity.getNORMT();
        if (NORMT != null) {
            stmt.bindString(5, NORMT);
        }
 
        String SPART = entity.getSPART();
        if (SPART != null) {
            stmt.bindString(6, SPART);
        }
 
        String MAKTX = entity.getMAKTX();
        if (MAKTX != null) {
            stmt.bindString(7, MAKTX);
        }
 
        String ZMAKTX = entity.getZMAKTX();
        if (ZMAKTX != null) {
            stmt.bindString(8, ZMAKTX);
        }
 
        String ZEINR = entity.getZEINR();
        if (ZEINR != null) {
            stmt.bindString(9, ZEINR);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MaterialModel entity) {
        stmt.clearBindings();
 
        String MATNR = entity.getMATNR();
        if (MATNR != null) {
            stmt.bindString(1, MATNR);
        }
 
        String MTART = entity.getMTART();
        if (MTART != null) {
            stmt.bindString(2, MTART);
        }
 
        String MATKL = entity.getMATKL();
        if (MATKL != null) {
            stmt.bindString(3, MATKL);
        }
 
        String BISMT = entity.getBISMT();
        if (BISMT != null) {
            stmt.bindString(4, BISMT);
        }
 
        String NORMT = entity.getNORMT();
        if (NORMT != null) {
            stmt.bindString(5, NORMT);
        }
 
        String SPART = entity.getSPART();
        if (SPART != null) {
            stmt.bindString(6, SPART);
        }
 
        String MAKTX = entity.getMAKTX();
        if (MAKTX != null) {
            stmt.bindString(7, MAKTX);
        }
 
        String ZMAKTX = entity.getZMAKTX();
        if (ZMAKTX != null) {
            stmt.bindString(8, ZMAKTX);
        }
 
        String ZEINR = entity.getZEINR();
        if (ZEINR != null) {
            stmt.bindString(9, ZEINR);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MaterialModel readEntity(Cursor cursor, int offset) {
        MaterialModel entity = new MaterialModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // MATNR
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // MTART
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // MATKL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // BISMT
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // NORMT
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // SPART
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // MAKTX
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ZMAKTX
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // ZEINR
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MaterialModel entity, int offset) {
        entity.setMATNR(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMTART(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMATKL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBISMT(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNORMT(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSPART(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMAKTX(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setZMAKTX(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setZEINR(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MaterialModel entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MaterialModel entity) {
        return null;
    }

    @Override
    public boolean hasKey(MaterialModel entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
