package com.xx.chinetek.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xx.chinetek.model.Base.SyncParaModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SYNC_PARA_MODEL".
*/
public class SyncParaModelDao extends AbstractDao<SyncParaModel, Void> {

    public static final String TABLENAME = "SYNC_PARA_MODEL";

    /**
     * Properties of entity SyncParaModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ParaID = new Property(0, String.class, "ParaID", false, "PARA_ID");
        public final static Property ParaName = new Property(1, String.class, "ParaName", false, "PARA_NAME");
        public final static Property ParaContext = new Property(2, String.class, "ParaContext", false, "PARA_CONTEXT");
    }


    public SyncParaModelDao(DaoConfig config) {
        super(config);
    }
    
    public SyncParaModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SYNC_PARA_MODEL\" (" + //
                "\"PARA_ID\" TEXT UNIQUE ," + // 0: ParaID
                "\"PARA_NAME\" TEXT," + // 1: ParaName
                "\"PARA_CONTEXT\" TEXT);"); // 2: ParaContext
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SYNC_PARA_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SyncParaModel entity) {
        stmt.clearBindings();
 
        String ParaID = entity.getParaID();
        if (ParaID != null) {
            stmt.bindString(1, ParaID);
        }
 
        String ParaName = entity.getParaName();
        if (ParaName != null) {
            stmt.bindString(2, ParaName);
        }
 
        String ParaContext = entity.getParaContext();
        if (ParaContext != null) {
            stmt.bindString(3, ParaContext);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SyncParaModel entity) {
        stmt.clearBindings();
 
        String ParaID = entity.getParaID();
        if (ParaID != null) {
            stmt.bindString(1, ParaID);
        }
 
        String ParaName = entity.getParaName();
        if (ParaName != null) {
            stmt.bindString(2, ParaName);
        }
 
        String ParaContext = entity.getParaContext();
        if (ParaContext != null) {
            stmt.bindString(3, ParaContext);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SyncParaModel readEntity(Cursor cursor, int offset) {
        SyncParaModel entity = new SyncParaModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ParaID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ParaName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // ParaContext
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SyncParaModel entity, int offset) {
        entity.setParaID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setParaName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParaContext(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SyncParaModel entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SyncParaModel entity) {
        return null;
    }

    @Override
    public boolean hasKey(SyncParaModel entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
